version: '3.5'

services:
  Project_My_ChatGPT:
    image: chatgpt-clone
    container_name: Project_My_ChatGPT
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1338:1338"
